/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Documentation
         * @description Documentation page for the CryptoSharia API using Scalar.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API Documentation Page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI Spec
         * @description Retrieve the OpenAPI 3.1.0 specification for this API.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI Specification in JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign In
         * @description Authenticate with email and password. Returns access and refresh tokens.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthSigninPostBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["AuthSigninPostResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Out
         * @description Revoke a refresh token to end a session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthSignoutPostBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: {
                                success: boolean;
                                message: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Rotate refresh token and issue a new access token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthRefreshPostBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["AuthRefreshPostResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Retrieve profile information for the currently authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["AuthMeGetResponse"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Posts
         * @description Retrieve a list of posts with filtering, searching, and pagination support.
         */
        get: {
            parameters: {
                query?: {
                    /** @description List of content statuses to filter by.<br>Example: published,draft */
                    statuses?: ("draft" | "published" | "archived")[];
                    /** @description List of post sections to filter by.<br>Example: news,education,activity */
                    sections?: ("news" | "education" | "research" | "activity")[];
                    /** @description List of post types to filter by.<br>Example: article,video,webinar */
                    types?: ("article" | "webinar" | "video" | "headline")[];
                    /** @description List of post slugs to filter by.<br>Example: this-is-a-post,this-is-another-post */
                    slugs?: string[];
                    /** @description List of post slugs to exclude.<br>Example: this-is-a-post,this-is-another-post */
                    exclude?: string[];
                    search?: string;
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PaginatedPostsGetItem"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Post by ID
         * @description Retrieve any post using its UUID regardless of its status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The UUID of the post */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PostsGetData"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Published Post by Slug
         * @description Retrieve a single published post using its slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The slug of the post */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PostsGetData"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tokens
         * @description Retrieve a list of cryptocurrency tokens with filtering, searching, and pagination support.
         */
        get: {
            parameters: {
                query?: {
                    /** @description List of content statuses to filter by.<br>Example: published,draft */
                    statuses?: ("draft" | "published" | "archived")[];
                    /** @description List of sharia statuses to filter by.<br>Example: halal,haram */
                    shariaStatuses?: ("halal" | "haram" | "syubhat")[];
                    /** @description List of token slugs to filter by.<br>Example: bitcoin,ethereum,sui */
                    slugs?: string[];
                    /** @description List of token slugs to exclude.<br>Example: bitcoin,ethereum,sui */
                    exclude?: string[];
                    search?: string;
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PaginatedTokensGetItem"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token by ID
         * @description Retrieve any cryptocurrency token using its UUID regardless of its status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The UUID of the cryptocurrency token */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["TokensGetData"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Published Token by Slug
         * @description Retrieve a single published cryptocurrency token using its slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The slug of the cryptocurrency token */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["TokensGetData"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token Quotes
         * @description Fetch real-time quotes and market data for specific tokens from CoinMarketCap.
         */
        get: {
            parameters: {
                query: {
                    /** @description List of token slugs to get quotes for.<br>Example: bitcoin,ethereum,sui */
                    slugs: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["TokensQuotesGetItem"][];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description Retrieve a list of messages with support for search, sender filtering, and pagination.
         */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    /** @description List of sender emails to filter by.<br>Example: example1@gmail.com,example2@gmail.com */
                    senders?: string[];
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PaginatedMessagesGetItem"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Send Message
         * @description Create a new message from the contact form.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Whether to trigger an external notification (e.g. email) */
                    notify?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MessagesPostBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                /** Format: email */
                                email: string;
                                message: string;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imgbb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image to ImgBB
         * @description Proxies an image upload to the ImgBB service and gets the resulting URLs.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description The image file to upload
                         */
                        image?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: {
                                /** Format: uuid */
                                id: string;
                                imgbbId: string;
                                title: string;
                                url: string;
                                width: number;
                                height: number;
                                size: number;
                                fileName: string;
                                mimeType: string;
                                deleteUrl: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: uuid */
                                createdBy: string | null;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Sample Data
         * @description Initialize the database with sample data for development and testing purposes. (Seeding in production is forbidden)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Successful signin response with tokens and user info */
        AuthSigninPostResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            avatarUrl: string | null;
            isActive: boolean;
            twoFactorSecret: string | null;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            /** Format: uuid */
            createdBy: string | null;
            /** Format: uuid */
            updatedBy: string | null;
            /** @description The enum value of the assigned role */
            role: string | null;
            accessToken: string;
            refreshToken: string;
        };
        ApiResponse: {
            success: boolean;
            message: string;
            errors?: {
                [key: string]: string[];
            };
            data?: unknown;
        };
        /** @description Credentials for signing in */
        AuthSigninPostBody: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthSignoutPostBody: {
            /** @description The refresh token to revoke */
            refreshToken: string;
        };
        /** @description Successful token refresh */
        AuthRefreshPostResponse: {
            user: {
                /** Format: uuid */
                id: string;
                name: string;
                email: string;
                avatarUrl: string | null;
                /** Format: uuid */
                roleId: string | null;
                isActive: boolean;
                twoFactorSecret: string | null;
                /** Format: date-time */
                lastLoginAt: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string | null;
                /** Format: uuid */
                createdBy: string | null;
                /** Format: uuid */
                updatedBy: string | null;
            };
            accessToken: string;
            refreshToken: string;
        };
        AuthRefreshPostBody: {
            /** @description The opaque refresh token */
            refreshToken: string;
        };
        /** @description Successful retrieval of current user info */
        AuthMeGetResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            avatarUrl: string | null;
            isActive: boolean;
            twoFactorSecret: string | null;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            /** Format: uuid */
            createdBy: string | null;
            /** Format: uuid */
            updatedBy: string | null;
            role: components["schemas"]["RoleMetadata"];
            /** @description List of programmatic permission keys */
            permissions: string[];
        };
        /** @description The metadata of the assigned role */
        RoleMetadata: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        } | null;
        PaginatedPostsGetItem: {
            items: components["schemas"]["PostsGetItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        PostsGetItem: {
            /** Format: uuid */
            id: string;
            title: string;
            slug: string;
            excerpt: string;
            /** @enum {string} */
            section: "news" | "education" | "research" | "activity";
            /** @enum {string} */
            type: "article" | "webinar" | "video" | "headline";
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            isFeatured: boolean;
            /** Format: date-time */
            eventDate: string | null;
            externalLink: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            createdBy: components["schemas"]["UserMetadata"];
            updatedBy: components["schemas"]["UserMetadata"];
            coverImage: components["schemas"]["AssetMetadata"];
        };
        UserMetadata: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        } | null;
        AssetMetadata: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            filename: string;
            size: number;
            mimeType?: string | null;
            width?: number | null;
            height?: number | null;
        };
        Pagination: {
            /** @description Total number of items matching the filters */
            total: number;
            /** @description Current page number */
            page: number;
            /** @description Number of items per page */
            limit: number;
            /** @description Total number of pages */
            totalPages: number;
        };
        PostsGetData: {
            /** Format: uuid */
            id: string;
            title: string;
            slug: string;
            excerpt: string;
            content: string;
            /** @enum {string} */
            section: "news" | "education" | "research" | "activity";
            /** @enum {string} */
            type: "article" | "webinar" | "video" | "headline";
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            isFeatured: boolean;
            /** Format: date-time */
            eventDate: string | null;
            externalLink: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            createdBy: components["schemas"]["UserMetadata"];
            updatedBy: components["schemas"]["UserMetadata"];
            coverImage: components["schemas"]["AssetMetadata"];
        };
        PaginatedTokensGetItem: {
            items: components["schemas"]["TokensGetItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        TokensGetItem: {
            /** Format: uuid */
            id: string;
            slug: string;
            rank: number;
            name: string;
            ticker: string;
            /** @enum {string} */
            shariaStatus: "halal" | "haram" | "syubhat";
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            excerpt: string;
            tradingviewSymbol: string | null;
            website: string;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            createdBy: components["schemas"]["UserMetadata"];
            updatedBy: components["schemas"]["UserMetadata"];
            logo: components["schemas"]["AssetMetadata"];
        };
        TokensGetData: {
            /** Format: uuid */
            id: string;
            slug: string;
            rank: number;
            name: string;
            ticker: string;
            /** @enum {string} */
            shariaStatus: "halal" | "haram" | "syubhat";
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            excerpt: string;
            tradingviewSymbol: string | null;
            website: string;
            content: string;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            createdBy: components["schemas"]["UserMetadata"];
            updatedBy: components["schemas"]["UserMetadata"];
            logo: components["schemas"]["AssetMetadata"];
        };
        TokensQuotesGetItem: {
            slug: string;
            rank: number;
            infiniteSupply: boolean;
            maxSupply: number | null;
            circulatingSupply: number;
            priceUsd: number;
            marketCapUsd: number;
            marketCapDominance: number;
            percentChange24h: number;
        };
        PaginatedMessagesGetItem: {
            items: components["schemas"]["MessagesGetItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        MessagesGetItem: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        MessagesPostBody: {
            name: string;
            /** Format: email */
            email: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
